language: ruby
rvm: 2.6.4
sudo: false
services:
- xvfb
script:
- bundle exec rspec
- bundle exec cucumber
deploy:
  provider: heroku
  api_key:
    secure: SjsbOtphtUoTfUSRkwSSdCBotTYvx5+OJSB4i+oAJ7URD/HJPqHG4Q9NxBCmyHF8rmYTSUvMqr2t+sYZEYXeicBeLwsL6Fzg4WPPv3NifzPgMW66PU9FBTxcvXvDyt9N1jIBQA/Fr4I2lZJhx7zmCEYcuxooSDH4FIx3Z+/ZOiAtafkyBv4uYHShKP2VQEDGxuQeWa0y3Y8nQWlAWbaE8MWgtrPMYlcHmsJoCiJ4Yitif7ZrE1QhPeUFlrbxTDp4KX5SeTcHQI6MfOrOrejwku0hmarApioZ0A7xSkHSNRMvaC2hlUuZZC4J+8lNTIYzahBWZIfKp8FeGKPzvJE/ipt/iqpn1atQBOL29LqylXrqoSqWGauKd+iR+VNR4Ser57DyjtxxeB6aHXfwfcK4TzU141m0pabZDpRpBNDM2QV5iuSQB7Sy35b5QJvWHJpPisMCOa4/Mm1SLwT1ScyGsqrnBDptgmZq/BlFcAb91WXRAn41TmYPhlQ/5C4dnwmdn9L2xTvc+z65VDeoiIRjElsta5yoPVBADJCa4LKa58b3waPd11WQzcGCISqd2PDczMKFqO3UMPmQw33JkB2tlnN3jAMtJxfZw3bX/8Yi2iLKgUyiesoM3oRvNFTl6Luh1gGXVjFU1gzPkl2SUzmjWJhVSajrzY57QvhmiOZEpe8=
  app: kleer-test
  on:
    repo: kleer-la/website17
    branch: develop
  app: kleer
  on:
    repo: kleer-la/website17
    branch: master
