language: ruby
rvm: 2.6.7
sudo: false
services:
- xvfb
script:
- bundle exec rspec
- bundle exec cucumber
deploy:
  provider: heroku
  api_key:
    secure: Sr98B2WEh7MeHwBpNGXR+u7+7r0MKelU1/PZPRez6OhA3dDJdgnPsP25uStX8G4FKOuBhiUCM2jlpFUWWkjH43blqVooHDBKuhkS1siPctFrVeP5FUOZJJNmc0X9ID2vk0G4u2hNpuEsm0D3VnGDNV+/y6ujuaRnpFo2IJ4XxAZZBBtDJDNdnEUEvf3qLHOfFLlruLKTVQW01251M0LUUnCK2pjt9jKIxMusDf/+e+IqmhPPHKcvSbFEBESB4CHlkcuGNia0DgIGvKJXPpdO39Yx+oZ30S9hW5oQ1buqTJtkP4ywuTX4nJpjvcsTkeEGIMdmYgrySLwetagPydbHrhN7tPF+rs4HG1ZbsMFFNlUv1lgm6SMD2Y0SjGTBfzo7LHm2yEYUh75p9WG93YQN+YahIZ2Zr6GX79+F9J7kPr4Tk5GWwfAwUcrBNEifQXT1rkLIxT43INCrQZ3M38FYXtE67H0a2YK9aAS8vCMug1DsHIbUEqW8dp6zhyOquBMtMuCJOO6c1tDZsOwlqmPXNuaTigy8h9vWHnTb5HfQjjFxXErSPd7S+MrytVfQebCE/12siYzk089+LpUrHN2rIRAvKjgCLJ9ndRzhu+cbVt1srP+ASgdvn1KORjUWCqvYnJZ6VAfBNB69SakB2Hldq7DPXBkRWpOqd7P/f/FpG3c=
  app:
    develop: kleer-test
    master: kleer
