language: ruby
rvm: 1.9.3
sudo: false
before_script:
- sh -e /etc/init.d/xvfb start
script:
- bundle exec rspec
- bundle exec cucumber
deploy:
  provider: heroku
  api_key:
    secure: bHmRLBWs+CHoOOKF95+1SDS0Wkx6BkxRKljALElD7dCDgeX1dGEu/aDGoSm60HXFcWpOVMCQMyoMUrPOTLhW3ppfrT6MrEph3gQoE0aTdnVREpwZDmwXGCs+S+tqj/vJw+xgga3X2qmUt/GYXmsO38n9iHwbRoVgeVGCXXiBhTC4KFwrj7kGlWPWe+tfbG9Qkd+KCyE7vE3Kqan0/FgpQsNClcsq6mWnDviPwJCbdumAeiIeYn5V/3TFHAMDcZcPEYkBQkc4riIy4m4IDiafdgWP6gGTn7qdqMimBslIXzbFceWoCIA2VxdA0dRolz0XGMl4paTjVanZc8mu4vF8kiZQ58UKKOwJC6KGtUldt3N96UOzUwJ9nLwpMusiOnwDrFRsgLQGKISL2Oxs/Y5mAOCWODDI/Gc5Op19xU2dgyPkWIwUCM+v/21oRcjHBjIc6j8m3OOG+5JP/wVizm0nvK6yYvas97bAfdJslrafaPNLCxX2L7hiIG/su1Eg4CKmBEu9kZap36XUR8TR4W+A7n7h8sLBS59RSNJDqYNuFEXNUQR9iSK7vV5SB471Vlz3yOH/GvmiKFuyJvWCzBL6IwhzotO/w6k01ZEuowDo0pTIt3BRobptIAALImZiJ9jCBR7pqrBjh7timEb/iJUyLJtLPsKl758ukO/yzLA3AsQ=
  app:
    develop: qa17
