language: ruby
rvm: 2.6.4
sudo: false
before_script:
- sh -e /etc/init.d/xvfb start
script:
- bundle exec rspec
- bundle exec cucumber
deploy:
  provider: heroku
  api_key:
    secure: Je7kDogSF2Xt6HG434KPkSo2vEcop4vtAdK5WJmlJ2tePDRfXZKC8KnDjmg2pVbqwCzMAcqx0A5b9xuwFaS/GZDIccpqUc1a2XsIC5iW2Il/Cdg1NT/mps3ovCyN9jLgPI+bmC1c7ErYjyqHsJ3TylzdpkdTQ7s85rP83+x+7E18AqqmzwRk7bK/nVfmvTf84dHCuXSjQ5POaX3ebN79HdmV+b+Ivx80yauSJRrJvkhPjzDoM8mKyJzFFtkHNDh35e6k9Jiw9oAMVyoeC1lZzqgLEe+UMMZIF033OXelXEdrzOuN5hLA8QtRNvdR9U1cEyKyjeTc8NRuEqsVNuh6ryEEI4ODXXuUSvryQmOj9hcbqdp8ijv9lY5KV+c72Pe+UOPZHCmp9eVsb6LBbfZELaYcyxTl8FbXqGFY41RfYYRI52zxz/lhMPa2YzsX/2vw+6eIjuIOgbYDxFHMReb0t9vf44Ld3hg3LQZIcIFSpt+4ycSAOT7ePR6TkVOUHN1ZujvfhJr9zsUUtH9ghB4TEnU5R8EFqw4AXV0NIo7U/qNDW1MRYH+BTLURVfymvqQzRVcjQ080kJTpCvy715qtmI6Ik0pr1HOkwZ2b4rc9gsU2RYK6UEYpCi7eMjaC5b5ULlnA1lwKWiFxCIKs4ETQEF6W/j3yF8s2i3MPyGgQ9Xo=
  app:
    master: kleer
    develop: kleer-test
