language: ruby
rvm: 2.6.4
sudo: false
services:
- xvfb
script:
- bundle exec rspec
- bundle exec cucumber
deploy:
  provider: heroku
  api_key:
    secure: X8tr7cNHIksB41yvlNM68E5Slq7sdmbC0x2T5pBBaCGilwkdcUSZEQ8lsHrVTtB4517aYt+lES/zagw5j9aT7grp6UuhODLyC/HS74q+KBijg5+sa3Vdxgo8RU54yAcDbqz4pEr+7T7UBWm8bov2kEH76ANxaytVtjx5HUsOzlh6EWXceCrbBlbbfaYStZFqV8S1YHBb9vwSjVIkBJ9HJTM9/VuFtwCIEB2J/X5+WzrcmRNjBfgIhJBK1xQYJJKYzQJpWxnF7uFvCW8IqJj6cm2UQmLSRzqxgk1SnwnPDLB0MNYBgI/mCV2G3spD+HZR0a2xvui7FZiRpsqXeTBLrl682BzNiZwYxkfBgBi5Vj88wtfJyU0GkC6y2+fp3xP45zv+Dfmzv/qyQT9O3R2GPsDM7HD7Ch0XiayBDAUCE1GXeF7kYWEdbrJkS2otZgyX1fTbF3A6d4cjInPJjiKbxcW+bw1RxDqdvtryOVrrrq9kbmjibaOYlKPVAN0jrrsbGXiqJpXjd4YXBKDOEmE1zYNXY/ltwj2HfmNQWF+DdYWeJmHtDULSLTUpg9482kny0OcsvQzZ9WZkTQFE4o2KC47/XLp2zGXbhEZwPeJMhYl91zubJFRt0mo/qrlnKgciTfnOiopuQqwDLy52LnMNR6/1qz8OFNQiSuMqxtEhO6M=
app:
    master: kleer
    develop: kleer-test