def client_list
  [
    { name: 'Falabella Financiero', img: '/img/clientes/FalabellaFinanciero.webp' },
    { name: 'Telefonica', img: '/img/clientes/Telefonica.webp' },
    { name: 'Roche', img: '/img/clientes/Roche.webp' },
    { name: 'Scotiabank', img: '/img/clientes/Scotiabank.webp' },
    { name: 'Sura', img: '/img/clientes/sura.webp' },
    { name: 'Cementos Argos', img: '/img/clientes/argos.webp' },
    # {name: "BBVA Continental", img:"/img/clientes/BBVA.webp" },
    # {name: 'Coca-cola', img: '/img/clientes/coca.webp'},
    # {name: 'Disney', img: '/img/clientes/disney.webp'},
    # {name: 'Loreal París', img: '/img/clientes/loreal.webp'},
    { name: 'Ecopetrol', img: '/img/clientes/EcoPetrol.webp' },
    { name: 'Grupo Nutresa', img: '/img/clientes/grupoNutresa.webp' },
    { name: 'Terpel', img: '/img/clientes/terpel.webp' },
    { name: 'BCI', img: '/img/clientes/BCi.webp' }
    # {name: "Ecopetrol", img:"/img/clientes/Ecopetrol.png" },

    # {name: 'LATAM', img: '/img/clientes/latam.webp'},
    # {name: "epm", img:"/img/clientes/epm.webp" },
    # {name: "Protección", img:"/img/clientes/proteccion.webp" },
    # {name: "Banco de Occidente", img:"/img/clientes/ban_occidente.webp" },
    # {name: "Banco de Chile", img:"/img/clientes/BancoDeChileB.webp" },
    # # {name: "Banchile", img:"/img/clientes2/" },
    # {name: "Interbank", img:"/img/clientes/interbank.webp" },
    # {name: "BCP", img:"/img/clientes/BCP.webp" },
    # {name: "Interbanking", img:"/img/clientes/interbanking.webp" },
    # {name: "Grupo Galicia", img:"/img/clientes/galicia.webp" },
    # {name: "OSDE", img:"/img/clientes/osde.webp" },
    # # {name: "Cablevisión", img:"/img/clientes/logo-cablevision.png" },
    # {name: "Fibertel", img:"/img/clientes/fibertel.webp" },
    # {name: "YPF" , img:"/img/clientes/YPF.webp" },
    # {name: "Oracle", img:"/img/clientes/oracle.webp" },
    # {name: "Artear", img:"/img/clientes/artear.webp" },
    # # {name: "Telecom", img:"/img/clientes/logo-telecom.jpg" },
    # {name: "Farmacity", img:"/img/clientes/farmacity.webp" },
    # {name: "Cencosud", img:"/img/clientes/cencosud.webp" },
    # {name: "Plataforma 10", img: "/img/clientes/plataforma10.webp" },
    # {name: "Intraway", img: "/img/clientes/intraway.webp" },
    # {name: "Exxon Mobil", img: "/img/clientes/exxo_mobil.webp" },
    # {name: "Technisys", img: "/img/clientes/technisys.webp" },
    # {name: "GlobalLogic", img: "/img/clientes/global_logic.webp" },
    # # {name: "Neoris", img: "/img/clientes/logo-neoris.png" },
    # {name: "Asesuisa", img: "/img/clientes/asesuisa.webp" },
    # {name: "Bancolombia", img: "/img/clientes/bancolombia.webp" },
    # {name: "Colpatria", img: "/img/clientes/colpatria.webp" },
    # {name: "Edenor", img: "/img/clientes/edenor.webp" },
  ]
end
